server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bss-core
          uri: http://localhost:8081         # 先写死地址，未来换 lb://bss-core
          predicates:
            - Path=/api/**                   # 业务接口都转到 bss-core
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE
    nacos:
      server-addr: 127.0.0.1:8848
    inetutils:
      ignored-interfaces:
        - VMware.*
        - veth.*
        - VirtualBox.*
  # 直接把 JWT 公钥/密钥放配置（演示用，生产放 Secret）
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/auth/jwks # 用RSA并提供JWKS端点