server:
  port: 8082

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.3.16:8848
    inetutils:
      ignored-interfaces:
        - VMware.*
        - veth.*
        - VirtualBox.*
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: C##BSS_DATA
    password: 123456
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000  # 30s，避免无限等
      leak-detection-threshold: 15000

logging:
  level:
    com.zaxxer.hikari: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

auth:
  keys:
    load-from: memory   # ← 关键：使用内存生成

  jwt:
    ttl-seconds: 604800




management.endpoints.web.exposure.include: health,info